#pragma once
#ifndef MFLOW_MFLOW_CONFIG_H_INCLUDED
#define MFLOW_MFLOW_CONFIG_H_INCLUDED

#include "esp_log.h"

#define MFLOW_MESSAGE_PUSH_ATTEMPT_TIMEOUT_MS    (100)

#define MFLOW_NOTIFICATION_MASK_PROCESS_START    (0x00000001)
#define MFLOW_NOTIFICATION_MASK_PROCESS_SHUTDOWN (0x00000002)
#define MFLOW_NOTIFICATION_MASK_MESSAGE_ARRIVAL  (0x00000004)
#define MFLOW_NOTIFICATION_MASK_PROCESS_RESUME   (0x00000008)

#endif // MFLOW_MFLOW_CONFIG_H_INCLUDED
